name: Cypress Tests
run-name: ${{ github.actor }} is testing E2E tests 🚀
on: [push, workflow_dispatch]
jobs:
  Run-Cypress-E2E-Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Install node
        run: sudo apt install nodejs

      - name: Checkout repository code
        uses: actions/checkout@v3

      - name: Intall dependencies
        run: npm install

      - name: Run api tests
        run: npm run test:api

      - name: Run cypress test
        run: npm run cy:run
